apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: local-cluster
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: argo-rollouts
    repoURL: https://github.com/markmckie/local-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
